/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VietnamRouteImport } from './routes/vietnam'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SlbRouteImport } from './routes/slb'
import { Route as RconRouteImport } from './routes/rcon'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthSteamLoginRouteImport } from './routes/auth/steam/login'
import { Route as AuthSteamCallbackRouteImport } from './routes/auth/steam/callback'
import { Route as AuthEpicLoginRouteImport } from './routes/auth/epic/login'
import { Route as AuthEpicCallbackRouteImport } from './routes/auth/epic/callback'
import { Route as AuthDiscordLoginRouteImport } from './routes/auth/discord/login'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth/discord/callback'

const VietnamRoute = VietnamRouteImport.update({
  id: '/vietnam',
  path: '/vietnam',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SlbRoute = SlbRouteImport.update({
  id: '/slb',
  path: '/slb',
  getParentRoute: () => rootRouteImport,
} as any)
const RconRoute = RconRouteImport.update({
  id: '/rcon',
  path: '/rcon',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamLoginRoute = AuthSteamLoginRouteImport.update({
  id: '/auth/steam/login',
  path: '/auth/steam/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSteamCallbackRoute = AuthSteamCallbackRouteImport.update({
  id: '/auth/steam/callback',
  path: '/auth/steam/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEpicLoginRoute = AuthEpicLoginRouteImport.update({
  id: '/auth/epic/login',
  path: '/auth/epic/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEpicCallbackRoute = AuthEpicCallbackRouteImport.update({
  id: '/auth/epic/callback',
  path: '/auth/epic/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordLoginRoute = AuthDiscordLoginRouteImport.update({
  id: '/auth/discord/login',
  path: '/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/rcon': typeof RconRoute
  '/slb': typeof SlbRoute
  '/stats': typeof StatsRoute
  '/vietnam': typeof VietnamRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/epic/callback': typeof AuthEpicCallbackRoute
  '/auth/epic/login': typeof AuthEpicLoginRoute
  '/auth/steam/callback': typeof AuthSteamCallbackRoute
  '/auth/steam/login': typeof AuthSteamLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/rcon': typeof RconRoute
  '/slb': typeof SlbRoute
  '/stats': typeof StatsRoute
  '/vietnam': typeof VietnamRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/epic/callback': typeof AuthEpicCallbackRoute
  '/auth/epic/login': typeof AuthEpicLoginRoute
  '/auth/steam/callback': typeof AuthSteamCallbackRoute
  '/auth/steam/login': typeof AuthSteamLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/rcon': typeof RconRoute
  '/slb': typeof SlbRoute
  '/stats': typeof StatsRoute
  '/vietnam': typeof VietnamRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/epic/callback': typeof AuthEpicCallbackRoute
  '/auth/epic/login': typeof AuthEpicLoginRoute
  '/auth/steam/callback': typeof AuthSteamCallbackRoute
  '/auth/steam/login': typeof AuthSteamLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/members'
    | '/rcon'
    | '/slb'
    | '/stats'
    | '/vietnam'
    | '/auth/logout'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/epic/callback'
    | '/auth/epic/login'
    | '/auth/steam/callback'
    | '/auth/steam/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/members'
    | '/rcon'
    | '/slb'
    | '/stats'
    | '/vietnam'
    | '/auth/logout'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/epic/callback'
    | '/auth/epic/login'
    | '/auth/steam/callback'
    | '/auth/steam/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/members'
    | '/rcon'
    | '/slb'
    | '/stats'
    | '/vietnam'
    | '/auth/logout'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/epic/callback'
    | '/auth/epic/login'
    | '/auth/steam/callback'
    | '/auth/steam/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  RconRoute: typeof RconRoute
  SlbRoute: typeof SlbRoute
  StatsRoute: typeof StatsRoute
  VietnamRoute: typeof VietnamRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
  AuthDiscordLoginRoute: typeof AuthDiscordLoginRoute
  AuthEpicCallbackRoute: typeof AuthEpicCallbackRoute
  AuthEpicLoginRoute: typeof AuthEpicLoginRoute
  AuthSteamCallbackRoute: typeof AuthSteamCallbackRoute
  AuthSteamLoginRoute: typeof AuthSteamLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vietnam': {
      id: '/vietnam'
      path: '/vietnam'
      fullPath: '/vietnam'
      preLoaderRoute: typeof VietnamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slb': {
      id: '/slb'
      path: '/slb'
      fullPath: '/slb'
      preLoaderRoute: typeof SlbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rcon': {
      id: '/rcon'
      path: '/rcon'
      fullPath: '/rcon'
      preLoaderRoute: typeof RconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam/login': {
      id: '/auth/steam/login'
      path: '/auth/steam/login'
      fullPath: '/auth/steam/login'
      preLoaderRoute: typeof AuthSteamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/steam/callback': {
      id: '/auth/steam/callback'
      path: '/auth/steam/callback'
      fullPath: '/auth/steam/callback'
      preLoaderRoute: typeof AuthSteamCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/epic/login': {
      id: '/auth/epic/login'
      path: '/auth/epic/login'
      fullPath: '/auth/epic/login'
      preLoaderRoute: typeof AuthEpicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/epic/callback': {
      id: '/auth/epic/callback'
      path: '/auth/epic/callback'
      fullPath: '/auth/epic/callback'
      preLoaderRoute: typeof AuthEpicCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/login': {
      id: '/auth/discord/login'
      path: '/auth/discord/login'
      fullPath: '/auth/discord/login'
      preLoaderRoute: typeof AuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  RconRoute: RconRoute,
  SlbRoute: SlbRoute,
  StatsRoute: StatsRoute,
  VietnamRoute: VietnamRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
  AuthDiscordLoginRoute: AuthDiscordLoginRoute,
  AuthEpicCallbackRoute: AuthEpicCallbackRoute,
  AuthEpicLoginRoute: AuthEpicLoginRoute,
  AuthSteamCallbackRoute: AuthSteamCallbackRoute,
  AuthSteamLoginRoute: AuthSteamLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
